DEFAULT_DISCORD_LINK = "https://discord.gg/rFrDA6veF"
TMDB_BASE_URL = "https://api.themoviedb.org/3"
TMDB_IMAGE_BASE_URL = "https://image.tmdb.org/t/p/w500"
IMDBAPI_BASE_URL = "https://api.imdbapi.dev"
BOOKMYSHOW_HOME_URL = "https://in.bookmyshow.com/"
KNOWN_BOOKMYSHOW_LINKS = {
    "cocktail 2": "https://in.bookmyshow.com/movies/mumbai/cocktail-2/ET00491386",
}
CURATED_UPCOMING_RELEASES = [
    {
        "title": "The Super Mario Galaxy Movie",
        "description": "Mario, Luigi, Peach, and friends return for a new animated adventure inspired by the Super Mario Galaxy games.",
        "language": "English, Hindi, Tamil, Telugu",
        "genre": "Adventure,Animation,Comedy,Family,Fantasy",
        "release_date": "2026-04-03",
        "rating": 0,
    },
    {
        "title": "Minions & Monsters",
        "description": "The Minions return for a new Illumination theatrical adventure packed with chaotic comedy, family-friendly mayhem, and monster-sized trouble.",
        "language": "English, Hindi, Tamil, Telugu",
        "genre": "Animation,Comedy,Family",
        "release_date": "2026-07-01",
        "rating": 0,
    },
    {
        "title": "Varanasi",
        "description": "A Telugu-led pan-Indian adventure drama scheduled for a wide multi-language theatrical rollout.",
        "language": "Telugu, Hindi, Tamil, Kannada, Malayalam",
        "genre": "Action,Adventure,Drama",
        "release_date": "2026-07-03",
        "rating": 0,
    },
    {
        "title": "The Paradise",
        "description": "A large-scale Telugu action drama listed among upcoming theatrical releases across Indian languages.",
        "language": "Telugu, Hindi, Tamil, Kannada, Malayalam",
        "genre": "Action,Drama",
        "release_date": "2026-07-09",
        "rating": 0,
    },
    {
        "title": "Balan: The Boy",
        "description": "A multi-language Indian drama arriving for family audiences across Malayalam, Kannada, Hindi, Tamil, and Telugu.",
        "language": "Malayalam, Kannada, Hindi, Tamil, Telugu",
        "genre": "Drama,Family",
        "release_date": "2026-07-10",
        "rating": 0,
    },
    {
        "title": "The Odyssey",
        "description": "Christopher Nolan's mythic epic brings Homer's legendary voyage to the big screen with large-scale adventure and spectacle.",
        "language": "English, Hindi, Tamil, Telugu",
        "genre": "Adventure,Drama,Fantasy",
        "release_date": "2026-07-17",
        "rating": 0,
    },
    {
        "title": "Carry on Jatta 4",
        "description": "The Punjabi comedy franchise returns with another round of family confusion, romance, and high-energy comic chaos.",
        "language": "Punjabi",
        "genre": "Comedy,Drama",
        "release_date": "2026-07-24",
        "rating": 0,
    },
    {
        "title": "Spider-Man: Brand New Day",
        "description": "Peter Parker begins a fresh chapter as Spider-Man, facing new pressure, new threats, and a dangerous evolution in his powers.",
        "language": "English, Hindi, Tamil, Telugu",
        "genre": "Action,Adventure,Superhero",
        "release_date": "2026-07-31",
        "rating": 0,
    },
    {
        "title": "Toy Story 5",
        "description": "Pixar's toys return for another animated theatrical adventure about friendship, change, and a new generation of play.",
        "language": "English, Hindi, Tamil, Telugu",
        "genre": "Adventure,Animation,Comedy,Family",
        "release_date": "2026-08-07",
        "rating": 0,
    },
    {
        "title": "Supergirl",
        "description": "Kara Zor-El steps into a new DC cinematic adventure with cosmic action, identity, and superhero stakes.",
        "language": "English, Hindi, Tamil, Telugu",
        "genre": "Action,Adventure,Sci-Fi,Superhero",
        "release_date": "2026-08-14",
        "rating": 0,
    },
    {
        "title": "Jindagi Once More",
        "description": "A Gujarati theatrical release centered on second chances, relationships, and rediscovering joy.",
        "language": "Gujarati",
        "genre": "Drama,Family",
        "release_date": "2026-08-07",
        "rating": 0,
    },
    {
        "title": "Welcome To The Jungle",
        "description": "A Hindi ensemble comedy-adventure built around chaos, action, and a large comic cast.",
        "language": "Hindi",
        "genre": "Comedy,Adventure",
        "release_date": "2026-08-14",
        "rating": 0,
    },
    {
        "title": "Tumbadchi Manjula",
        "description": "A Marathi theatrical release bringing drama and mystery to upcoming cinema listings.",
        "language": "Marathi",
        "genre": "Drama,Mystery",
        "release_date": "2026-08-21",
        "rating": 0,
    },
    {
        "title": "Toxic: A Fairy Tale for Grown-ups",
        "description": "A pan-Indian action drama led by Kannada cinema and planned for multiple Indian languages.",
        "language": "Kannada, Hindi, Tamil, Telugu, Malayalam",
        "genre": "Action,Drama",
        "release_date": "2026-08-28",
        "rating": 0,
    },
    {
        "title": "Evil Dead Burn",
        "description": "The Evil Dead franchise returns with a new horror chapter built for theatrical scares and genre fans.",
        "language": "English, Hindi, Tamil, Telugu",
        "genre": "Horror,Thriller",
        "release_date": "2026-09-04",
        "rating": 0,
    },
    {
        "title": "Cocktail 2",
        "description": "A Hindi romantic drama continuation aimed at multiplex audiences with music, relationships, and urban emotion.",
        "language": "Hindi",
        "genre": "Drama,Romance",
        "release_date": "2026-09-04",
        "rating": 0,
    },
    {
        "title": "Ranabaali",
        "description": "A Telugu-led multi-language release planned for South Indian and Hindi audiences.",
        "language": "Telugu, Tamil, Kannada, Malayalam, Hindi",
        "genre": "Action,Drama",
        "release_date": "2026-09-11",
        "rating": 0,
    },
    {
        "title": "Colony",
        "description": "A Korean-language theatrical listing for viewers looking beyond Indian and Hollywood releases.",
        "language": "Korean",
        "genre": "Drama,Thriller",
        "release_date": "2026-09-18",
        "rating": 0,
    },
    {
        "title": "Drishyam 3",
        "description": "The Hindi mystery-thriller franchise returns with another chapter of secrets, investigation, and family stakes.",
        "language": "Hindi",
        "genre": "Drama,Mystery,Thriller",
        "release_date": "2026-10-02",
        "rating": 0,
    },
    {
        "title": "Peddi",
        "description": "A Telugu sports-action drama scheduled as a major Indian theatrical release.",
        "language": "Telugu, Hindi, Tamil, Kannada, Malayalam",
        "genre": "Action,Drama,Sports",
        "release_date": "2026-10-09",
        "rating": 0,
    },
    {
        "title": "Maa Inti Bangaaram",
        "description": "A Telugu family drama planned for theatrical audiences looking for emotion, relationships, and heartfelt storytelling.",
        "language": "Telugu",
        "genre": "Drama,Family",
        "release_date": "2026-10-16",
        "rating": 0,
    },
    {
        "title": "Michael",
        "description": "A musical biographical drama following Michael Jackson's rise, artistry, and cultural impact.",
        "language": "English, Hindi",
        "genre": "Biography,Drama,Music",
        "release_date": "2026-10-03",
        "rating": 0,
    },
    {
        "title": "Avengers: Doomsday",
        "description": "Marvel heroes face the rising threat of Doctor Doom in the next major Avengers event from Marvel Studios.",
        "language": "English, Hindi, Tamil, Telugu",
        "genre": "Action,Adventure,Superhero",
        "release_date": "2026-12-18",
        "rating": 0,
    },
    {
        "title": "Dune: Part Three",
        "description": "The next chapter of Denis Villeneuve's Dune saga continues the desert epic with prophecy, politics, and interstellar war.",
        "language": "English, Hindi, Tamil, Telugu",
        "genre": "Adventure,Drama,Sci-Fi",
        "release_date": "2026-12-18",
        "rating": 0,
    },
    {
        "title": "Send Help",
        "description": "A survival thriller about danger, isolation, and desperate choices after a journey goes wrong.",
        "language": "English",
        "genre": "Adventure,Horror,Thriller",
        "release_date": "2026-12-25",
        "rating": 0,
    },
    {
        "title": "Athimanoharam",
        "description": "A Malayalam family drama planned around the festive season with a warm, relationship-driven story.",
        "language": "Malayalam",
        "genre": "Drama,Family",
        "release_date": "2026-12-24",
        "rating": 0,
    },
    {
        "title": "Rakkayie",
        "description": "A Tamil-led multi-language release planned for year-end audiences across South Indian languages.",
        "language": "Tamil, Telugu, Kannada, Malayalam, Hindi",
        "genre": "Action,Drama",
        "release_date": "2026-12-31",
        "rating": 0,
    },
    {
        "title": "Shrek 5",
        "description": "Shrek, Fiona, Donkey, and the next generation of Far Far Away return for a new DreamWorks animated adventure.",
        "language": "English, Hindi",
        "genre": "Animation,Adventure,Comedy",
        "release_date": "2027-06-30",
        "rating": 0,
    },
]
FEATURED_MOVIE_DETAILS = {
    "Project Hail Mary": {
        "description": "A lone astronaut wakes up aboard a spacecraft with no memory of his mission and realizes he may be humanity's last chance. Based on Andy Weir's bestselling novel, the film follows Ryland Grace as he pieces together a desperate interstellar mission, an impossible scientific mystery, and an unexpected first-contact friendship.",
        "language": "English, Hindi, Tamil, Telugu",
        "genre": "Adventure,Drama,Sci-Fi",
        "release_date": "2026-03-20",
        "rating": 8.2,
        "justwatch_url": "https://www.justwatch.com/in/search?q=Project%20Hail%20Mary",
    }
}
THEATER_NETWORK = [
    ("PVR: Orion Mall", "Bengaluru Urban", "Orion Mall, Brigade Gateway, Dr Rajkumar Road, Rajajinagar, Bengaluru", 11, 156),
    ("PVR: Phoenix Marketcity", "Bengaluru Urban", "Phoenix Marketcity, Whitefield Main Road, Mahadevapura, Bengaluru", 9, 172),
    ("PVR: Forum South Bengaluru", "Bengaluru Urban", "Forum South Mall, Kanakapura Road, Konanakunte, Bengaluru", 12, 148),
    ("PVR: Nexus Koramangala", "Bengaluru Urban", "Nexus Mall, Hosur Road, Koramangala, Bengaluru", 8, 168),
    ("INOX: Megaplex Mall of Asia", "Bengaluru Urban", "Byatarayanapura, Yelahanka Taluk, Bellary Road, Bengaluru", 12, 188),
    ("PVR: Vega City", "Bengaluru Urban", "Vega City Mall, Bannerghatta Main Road, Bengaluru", 7, 164),
    ("INOX: Garuda Mall", "Bengaluru Urban", "Garuda Mall, Magrath Road, Ashok Nagar, Bengaluru", 5, 142),
    ("PVR: Mantri Square", "Bengaluru Urban", "Mantri Square Mall, Sampige Road, Malleshwaram, Bengaluru", 6, 150),
    ("PVR: VR Bengaluru", "Bengaluru Urban", "VR Bengaluru, Whitefield Road, Mahadevapura, Bengaluru", 9, 180),
    ("GT World Cinemas", "Bengaluru Urban", "GT World Mall, Magadi Main Road, Bengaluru", 3, 132),
    ("PVR: Elements Mall", "Bengaluru Urban", "Elements Mall, Thanisandra Main Road, Nagavara, Bengaluru", 5, 146),
    ("Gopalan Cinemas: Arcade Mall", "Bengaluru Urban", "Gopalan Arcade Mall, Mysore Road, Bengaluru", 4, 138),
    ("PVR: Lulu Mall Bengaluru", "Bengaluru Urban", "Lulu Global Mall, Mysore Road, Rajajinagar, Bengaluru", 6, 190),
    ("INOX: Megaplex Mall of Asia", "Bengaluru Urban", "Byatarayanapura, Yelahanka Taluk, Bellary Road, Bengaluru", 12, 168),
    ("PVR: Orion Mall, Dr Rajkumar Road", "Bengaluru Urban", "Orion Mall, Brigade Gateway, Dr Rajkumar Road, Malleshwaram West, Bengaluru", 11, 158),
    ("Cinepolis: Nexus Shantiniketan", "Bengaluru Urban", "Nexus Shantiniketan Mall, ITPL Main Road, Whitefield, Bengaluru", 7, 146),
    ("PVR: Superplex Forum South", "Bengaluru Urban", "Forum South Mall, Kanakapura Road, Konanakunte, Bengaluru", 12, 154),
    ("PVR: Phoenix Marketcity", "Bengaluru Urban", "Phoenix Marketcity, Whitefield Main Road, Mahadevapura, Bengaluru", 9, 160),
    ("PVR: Nexus Koramangala", "Bengaluru Urban", "Nexus Mall, Koramangala, Bengaluru", 8, 150),
    ("PVR: Vega City", "Bengaluru Urban", "Vega City Mall, Bannerghatta Main Road, Bengaluru", 7, 148),
    ("INOX: Garuda Mall", "Bengaluru Urban", "Garuda Mall, Magrath Road, Ashok Nagar, Bengaluru", 5, 142),
    ("PVR: Vaishnavi Sapphire", "Bengaluru Urban", "Vaishnavi Sapphire Mall, Yeshwanthpur, Bengaluru", 6, 150),
    ("Cinepolis: Royal Meenakshi Mall", "Bengaluru Urban", "Royal Meenakshi Mall, Bannerghatta Road, Bengaluru", 6, 144),
    ("PVR: Soul Spirit Centro Mall", "Bengaluru Urban", "Bellandur, Bengaluru", 5, 138),
    ("PVR: MSR Elements Mall", "Bengaluru Urban", "Elements Mall, Thanisandra Main Road, Nagavara, Bengaluru", 5, 142),
    ("Gopalan Cinemas: Signature Mall", "Bengaluru Urban", "Old Madras Road, Bengaluru", 4, 132),
    ("Gopalan Cinemas: Grand Mall", "Bengaluru Urban", "Old Madras Road, Bengaluru", 4, 130),
    ("PVR: Aura Park Square", "Bengaluru Urban", "Park Square Mall, ITPL, Whitefield, Bengaluru", 5, 142),
    ("PVR: Bhartiya Mall of Bengaluru", "Bengaluru Urban", "Bhartiya City, Thanisandra Main Road, Bengaluru", 7, 150),
    ("INOX: Brookefield Mall", "Bengaluru Urban", "Brookefield Mall, Kundalahalli, Bengaluru", 4, 138),
    ("INOX: Central JP Nagar", "Bengaluru Urban", "Central Mall, JP Nagar, Bengaluru", 4, 136),
    ("Cinepolis: ETA Namma Mall", "Bengaluru Urban", "ETA Namma Mall, Binny Pete, Bengaluru", 5, 142),
    ("Cinepolis: Binnypet Mall", "Bengaluru Urban", "Binnypet, Bengaluru", 5, 140),
    ("Mukunda Theatre", "Bengaluru Urban", "Maruthi Sevanagar, Bengaluru", 1, 360),
    ("Urvashi Cinema", "Bengaluru Urban", "Lalbagh Road, Bengaluru", 1, 420),
    ("Rex Theatre", "Bengaluru Urban", "Brigade Road, Bengaluru", 1, 360),
    ("Balaji Theatre", "Bengaluru Urban", "Tavarekere, Bengaluru", 1, 340),
    ("Sri Krishna Digital 4K Cinema", "Bengaluru Urban", "KR Puram, Bengaluru", 1, 330),
    ("Vaibhav Theatre", "Bengaluru Urban", "Sanjay Nagar, Bengaluru", 1, 350),
    ("Navrang Theatre", "Bengaluru Urban", "Rajajinagar, Bengaluru", 1, 380),
    ("Veeresh Cinemas", "Bengaluru Urban", "Magadi Road, Bengaluru", 2, 300),
    ("Sri Sangameshwara Chitramandira", "Vijayapura (Bengaluru Rural)", "Vijayapura, Bengaluru Rural, Karnataka", 1, 420),
    ("Sri Gowrishankar Theatre", "Vijayapura (Bengaluru Rural)", "Vijayapura, Bengaluru Rural, Karnataka", 1, 380),
    ("Sri Vinayaka Cinemas", "Nelamangala (Bengaluru Rural)", "Nelamangala, Bengaluru Rural, Karnataka", 2, 260),
    ("Venkateshwara Theatre", "Devanahalli (Bengaluru Rural)", "Devanahalli, Bengaluru Rural, Karnataka", 1, 340),
    ("Sri Krishna Theatre", "Doddaballapur (Bengaluru Rural)", "Doddaballapur, Bengaluru Rural, Karnataka", 1, 360),
    ("Raghavendra Theatre", "Hoskote (Bengaluru Rural)", "Hoskote, Bengaluru Rural, Karnataka", 1, 320),
    ("Vijay Theatre", "Anekal (Bengaluru Urban/Rural)", "Anekal, Bengaluru region, Karnataka", 1, 300),
    ("Nandi Theatre", "Devanahalli (Bengaluru Rural)", "Devanahalli, Bengaluru Rural, Karnataka", 1, 320),
    ("Sri Lakshmi Theatre", "Nelamangala (Bengaluru Rural)", "Nelamangala, Bengaluru Rural, Karnataka", 1, 310),
    ("Sri Venkateshwara Chitra Mandira", "Doddaballapur (Bengaluru Rural)", "Doddaballapur, Bengaluru Rural, Karnataka", 1, 330),
    ("Sri Balaji Talkies", "Hoskote (Bengaluru Rural)", "Hoskote, Bengaluru Rural, Karnataka", 1, 300),
    ("Anjan Theatre", "Anekal (Bengaluru Urban/Rural)", "Anekal, Bengaluru region, Karnataka", 1, 300),
    ("PVR ICON: Phoenix Palladium", "Mumbai", "Phoenix Palladium, Lower Parel, Mumbai, Maharashtra", 8, 168),
    ("PVR: Market City Kurla", "Mumbai", "Phoenix Marketcity, Kurla West, Mumbai, Maharashtra", 9, 160),
    ("INOX: R-City Ghatkopar", "Mumbai", "R City Mall, Ghatkopar West, Mumbai, Maharashtra", 6, 148),
    ("Cinepolis: Viviana Mall", "Thane", "Viviana Mall, Eastern Express Highway, Thane, Maharashtra", 8, 156),
    ("MovieMax: Eternity Mall", "Thane", "Eternity Mall, Teen Hath Naka, Thane, Maharashtra", 5, 138),
    ("PVR: Oberoi Mall", "Mumbai", "Oberoi Mall, Goregaon East, Mumbai, Maharashtra", 6, 152),
    ("PVR: Select Citywalk", "Delhi", "Select Citywalk, Saket, Delhi", 6, 150),
    ("PVR: Vegas Dwarka", "Delhi", "Vegas Mall, Dwarka, Delhi", 12, 162),
    ("INOX: Nehru Place", "Delhi", "Nehru Place, Delhi", 4, 140),
    ("Cinepolis: Pacific NSP2", "Delhi", "Pacific Mall, Netaji Subhash Place, Delhi", 9, 150),
    ("PVR: Ambience Mall", "Gurugram", "Ambience Mall, NH 8, Gurugram, Haryana", 7, 154),
    ("INOX: Worldmark", "Gurugram", "Worldmark, Sector 65, Gurugram, Haryana", 6, 146),
    ("PVR: Logix City Centre", "Noida", "Logix City Centre Mall, Noida, Uttar Pradesh", 15, 160),
    ("Wave Cinemas: The Great India Place", "Noida", "The Great India Place Mall, Noida, Uttar Pradesh", 6, 142),
    ("PVR: Pacific Mall", "Ghaziabad", "Pacific Mall, Sahibabad, Ghaziabad, Uttar Pradesh", 7, 144),
    ("PVR: Lulu Mall", "Lucknow", "Lulu Mall, Amar Shaheed Path, Lucknow, Uttar Pradesh", 11, 158),
    ("INOX: Phoenix Palassio", "Lucknow", "Phoenix Palassio, Gomti Nagar Extension, Lucknow, Uttar Pradesh", 9, 150),
    ("PVR: Elante Mall", "Chandigarh", "Elante Mall, Industrial Area Phase 1, Chandigarh", 8, 158),
    ("PVR: VR Punjab", "Mohali", "VR Punjab Mall, Kharar Road, Mohali, Punjab", 7, 148),
    ("PVR: Pavilion Mall", "Ludhiana", "Pavilion Mall, Fountain Chowk, Ludhiana, Punjab", 7, 142),
    ("PVR: Alpha One Mall", "Amritsar", "Alpha One Mall, Amritsar, Punjab", 5, 138),
    ("PVR: Nexus Ahmedabad One", "Ahmedabad", "Nexus Ahmedabad One, Vastrapur, Ahmedabad, Gujarat", 7, 150),
    ("Cinepolis: Nexus Shantiniketan", "Ahmedabad", "Nexus Shantiniketan Mall, Ahmedabad, Gujarat", 6, 144),
    ("PVR: Acropolis Mall", "Ahmedabad", "Acropolis Mall, Thaltej, Ahmedabad, Gujarat", 5, 140),
    ("INOX: VR Mall", "Surat", "VR Mall, Dumas Road, Surat, Gujarat", 6, 146),
    ("Rajhans Cinemas: Adajan", "Surat", "Adajan, Surat, Gujarat", 5, 136),
    ("PVR: Eva Mall", "Vadodara", "Eva Mall, Manjalpur, Vadodara, Gujarat", 5, 134),
    ("INOX: South City Mall", "Kolkata", "South City Mall, Prince Anwar Shah Road, Kolkata, West Bengal", 6, 150),
    ("PVR: Mani Square", "Kolkata", "Mani Square Mall, EM Bypass, Kolkata, West Bengal", 6, 146),
    ("Cinepolis: Acropolis Mall", "Kolkata", "Acropolis Mall, Rajdanga Main Road, Kolkata, West Bengal", 5, 140),
    ("Miraj Cinemas: New Town", "Kolkata", "New Town, Kolkata, West Bengal", 4, 132),
    ("PVR: Nexus Esplanade", "Bhubaneswar", "Nexus Esplanade Mall, Rasulgarh, Bhubaneswar, Odisha", 7, 142),
    ("INOX: DN Regalia", "Bhubaneswar", "DN Regalia Mall, Patrapada, Bhubaneswar, Odisha", 5, 136),
    ("PVR: City Centre Mall", "Guwahati", "City Centre Mall, GS Road, Guwahati, Assam", 5, 138),
    ("INOX: Aurus Mall", "Guwahati", "Aurus Mall, Guwahati, Assam", 4, 130),
    ("PVR: Nexus Hyderabad", "Hyderabad", "Nexus Mall, Kukatpally, Hyderabad, Telangana", 9, 158),
    ("AMB Cinemas", "Hyderabad", "Gachibowli, Hyderabad, Telangana", 7, 168),
    ("Prasads Multiplex", "Hyderabad", "Necklace Road, Hyderabad, Telangana", 5, 180),
    ("PVR: Irrum Manzil", "Hyderabad", "Next Galleria Mall, Irrum Manzil, Hyderabad, Telangana", 7, 150),
    ("Asian Cinemas: M Cube Mall", "Hyderabad", "M Cube Mall, Attapur, Hyderabad, Telangana", 5, 142),
    ("PVR: VR Chennai", "Chennai", "VR Chennai, Anna Nagar, Chennai, Tamil Nadu", 10, 158),
    ("PVR: Grand Galada", "Chennai", "Grand Galada Mall, Pallavaram, Chennai, Tamil Nadu", 5, 140),
    ("INOX: Phoenix Marketcity", "Chennai", "Phoenix Marketcity, Velachery, Chennai, Tamil Nadu", 11, 162),
    ("AGS Cinemas: T Nagar", "Chennai", "T Nagar, Chennai, Tamil Nadu", 4, 146),
    ("Sathyam Cinemas", "Chennai", "Royapettah, Chennai, Tamil Nadu", 6, 170),
    ("PVR: Brookefields Mall", "Coimbatore", "Brookefields Mall, Coimbatore, Tamil Nadu", 6, 142),
    ("INOX: Prozone Mall", "Coimbatore", "Prozone Mall, Coimbatore, Tamil Nadu", 5, 138),
    ("PVR: Lulu Mall", "Kochi", "Lulu Mall, Edappally, Kochi, Kerala", 9, 154),
    ("Cinepolis: Centre Square Mall", "Kochi", "Centre Square Mall, MG Road, Kochi, Kerala", 7, 146),
    ("PVR: Forum Mall", "Kochi", "Forum Mall, Maradu, Kochi, Kerala", 8, 150),
    ("Carnival Cinemas: Mall of Travancore", "Thiruvananthapuram", "Mall of Travancore, Thiruvananthapuram, Kerala", 7, 142),
    ("PVR: Lulu Mall", "Thiruvananthapuram", "Lulu Mall, Akkulam, Thiruvananthapuram, Kerala", 12, 156),
    ("PVR: Pavilion Mall", "Pune", "Pavilion Mall, Shivajinagar, Pune, Maharashtra", 6, 148),
    ("Cinepolis: Seasons Mall", "Pune", "Seasons Mall, Magarpatta, Pune, Maharashtra", 10, 154),
    ("INOX: Bund Garden Road", "Pune", "Bund Garden Road, Pune, Maharashtra", 4, 138),
    ("PVR: Phoenix Marketcity", "Pune", "Phoenix Marketcity, Viman Nagar, Pune, Maharashtra", 9, 158),
    ("PVR: Nexus Westend", "Pune", "Nexus Westend Mall, Aundh, Pune, Maharashtra", 7, 150),
    ("PVR: Treasure Island", "Indore", "Treasure Island Mall, MG Road, Indore, Madhya Pradesh", 6, 142),
    ("INOX: C21 Mall", "Indore", "C21 Mall, AB Road, Indore, Madhya Pradesh", 5, 136),
    ("PVR: Aura Mall", "Bhopal", "Aura Mall, Shahpura, Bhopal, Madhya Pradesh", 5, 138),
    ("Cinepolis: DB Mall", "Bhopal", "DB Mall, Arera Hills, Bhopal, Madhya Pradesh", 6, 140),
    ("PVR: WTP", "Jaipur", "World Trade Park, Malviya Nagar, Jaipur, Rajasthan", 8, 148),
    ("INOX: GT Central", "Jaipur", "GT Central Mall, Malviya Nagar, Jaipur, Rajasthan", 6, 140),
    ("Raj Mandir Cinema", "Jaipur", "Bhagwan Das Road, Jaipur, Rajasthan", 1, 950),
    ("PVR: Celebration Mall", "Udaipur", "Celebration Mall, Udaipur, Rajasthan", 6, 138),
    ("PVR: Empress City Mall", "Nagpur", "Empress City Mall, Nagpur, Maharashtra", 5, 138),
    ("Cinepolis: VR Mall", "Nagpur", "VR Mall, Medical Square, Nagpur, Maharashtra", 6, 142),
    ("PVR: Magneto Mall", "Raipur", "Magneto Mall, Raipur, Chhattisgarh", 6, 138),
    ("INOX: Ambuja City Centre", "Raipur", "Ambuja City Centre Mall, Raipur, Chhattisgarh", 5, 132),
    ("PVR: Nucleus Mall", "Ranchi", "Nucleus Mall, Circular Road, Ranchi, Jharkhand", 5, 134),
    ("Fun Cinemas: Spring City Mall", "Ranchi", "Spring City Mall, Ranchi, Jharkhand", 4, 126),
    ("PVR: Patna Central", "Patna", "Patna Central Mall, Patna, Bihar", 5, 132),
    ("Cinepolis: P&M Mall", "Patna", "P&M Mall, Patliputra, Patna, Bihar", 4, 128),
    ("PVR: V Square Mall", "Varanasi", "V Square Mall, Varanasi, Uttar Pradesh", 5, 132),
    ("IP Cinemas: Sigra", "Varanasi", "Sigra, Varanasi, Uttar Pradesh", 4, 126),
    ("PVR: Z Square Mall", "Kanpur", "Z Square Mall, Kanpur, Uttar Pradesh", 6, 138),
    ("INOX: Rave 3", "Kanpur", "Rave 3 Mall, Kanpur, Uttar Pradesh", 4, 130),
    ("PVR: Civil Lines", "Prayagraj", "Civil Lines, Prayagraj, Uttar Pradesh", 4, 128),
    ("PVR: Trilium Mall", "Amritsar", "Trilium Mall, Amritsar, Punjab", 5, 136),
    ("PVR: City Centre", "Mangalore", "City Centre Mall, Mangalore, Karnataka", 6, 140),
    ("Cinepolis: Forum Fiza Mall", "Mangalore", "Forum Fiza Mall, Mangalore, Karnataka", 5, 134),
    ("PVR: Nexus Mall", "Mysuru", "Nexus Mall, Mysuru, Karnataka", 5, 136),
    ("DRC Cinemas", "Mysuru", "BM Habitat Mall, Jayalakshmipuram, Mysuru, Karnataka", 4, 132),
    ("PVR: Orion Uptown Mall", "Bengaluru", "Orion Uptown Mall, Old Madras Road, Bengaluru, Karnataka", 5, 140),
    ("INOX: Mantri Square", "Bengaluru", "Mantri Square Mall, Malleshwaram, Bengaluru, Karnataka", 6, 146),
]


INDIA_THEATER_CITIES = [
    ("Mumbai", "Maharashtra"),
    ("Delhi", "Delhi"),
    ("Hyderabad", "Telangana"),
    ("Chennai", "Tamil Nadu"),
    ("Kolkata", "West Bengal"),
    ("Pune", "Maharashtra"),
    ("Ahmedabad", "Gujarat"),
    ("Jaipur", "Rajasthan"),
    ("Lucknow", "Uttar Pradesh"),
    ("Kochi", "Kerala"),
    ("Coimbatore", "Tamil Nadu"),
    ("Surat", "Gujarat"),
    ("Vadodara", "Gujarat"),
    ("Indore", "Madhya Pradesh"),
    ("Bhopal", "Madhya Pradesh"),
    ("Nagpur", "Maharashtra"),
    ("Nashik", "Maharashtra"),
    ("Chandigarh", "Chandigarh"),
    ("Mohali", "Punjab"),
    ("Ludhiana", "Punjab"),
    ("Amritsar", "Punjab"),
    ("Gurugram", "Haryana"),
    ("Noida", "Uttar Pradesh"),
    ("Ghaziabad", "Uttar Pradesh"),
    ("Faridabad", "Haryana"),
    ("Patna", "Bihar"),
    ("Ranchi", "Jharkhand"),
    ("Raipur", "Chhattisgarh"),
    ("Bhubaneswar", "Odisha"),
    ("Guwahati", "Assam"),
    ("Mysuru", "Karnataka"),
    ("Mangalore", "Karnataka"),
    ("Madurai", "Tamil Nadu"),
    ("Trichy", "Tamil Nadu"),
    ("Vijayawada", "Andhra Pradesh"),
    ("Visakhapatnam", "Andhra Pradesh"),
    ("Thiruvananthapuram", "Kerala"),
    ("Kozhikode", "Kerala"),
    ("Kanpur", "Uttar Pradesh"),
    ("Varanasi", "Uttar Pradesh"),
    ("Prayagraj", "Uttar Pradesh"),
    ("Agra", "Uttar Pradesh"),
    ("Dehradun", "Uttarakhand"),
    ("Goa", "Goa"),
    ("Jodhpur", "Rajasthan"),
    ("Udaipur", "Rajasthan"),
    ("Rajkot", "Gujarat"),
    ("Jamshedpur", "Jharkhand"),
    ("Siliguri", "West Bengal"),
    ("Shillong", "Meghalaya"),
]

INDIA_THEATER_CHAINS = [
    ("PVR INOX", "Nexus Mall", 7, 154),
    ("Cinepolis", "City Centre", 6, 146),
    ("Miraj Cinemas", "Central Mall", 5, 136),
    ("MovieMax", "High Street", 4, 132),
    ("Carnival Cinemas", "Town Square", 4, 128),
]


def build_india_theater_network(target_count=200):
    network = []
    seen = set()

    for theater in THEATER_NETWORK:
        key = (theater[0].lower(), theater[1].lower())

        if key not in seen:
            network.append(theater)
            seen.add(key)

    if len(network) >= target_count:
        return network[:target_count]

    for city, state in INDIA_THEATER_CITIES:
        for chain, venue, screens, seats in INDIA_THEATER_CHAINS:
            name = f"{chain}: {venue} {city}"
            key = (name.lower(), city.lower())

            if key in seen:
                continue

            network.append((
                name,
                city,
                f"{venue}, {city}, {state}",
                screens,
                seats,
            ))
            seen.add(key)

            if len(network) >= target_count:
                return network

    return network


THEATER_NETWORK = build_india_theater_network(200)

THEATER_RENAMES = {
    "CineVerse Orion Mall": ("PVR: Orion Mall", "Bengaluru Urban", "Orion Mall, Brigade Gateway, Dr Rajkumar Road, Rajajinagar, Bengaluru"),
    "CineVerse Phoenix Marketcity": ("PVR: Phoenix Marketcity", "Bengaluru Urban", "Phoenix Marketcity, Whitefield Main Road, Mahadevapura, Bengaluru"),
    "CineVerse Forum South": ("PVR: Forum South Bengaluru", "Bengaluru Urban", "Forum South Mall, Kanakapura Road, Konanakunte, Bengaluru"),
    "CineVerse Nexus Koramangala": ("PVR: Nexus Koramangala", "Bengaluru Urban", "Nexus Mall, Hosur Road, Koramangala, Bengaluru"),
    "CineVerse Mall of Asia": ("INOX: Megaplex Mall of Asia", "Bengaluru Urban", "Byatarayanapura, Yelahanka Taluk, Bellary Road, Bengaluru"),
    "CineVerse Vega City": ("PVR: Vega City", "Bengaluru Urban", "Vega City Mall, Bannerghatta Main Road, Bengaluru"),
    "CineVerse Garuda Mall": ("INOX: Garuda Mall", "Bengaluru Urban", "Garuda Mall, Magrath Road, Ashok Nagar, Bengaluru"),
    "CineVerse Mantri Square": ("PVR: Mantri Square", "Bengaluru Urban", "Mantri Square Mall, Sampige Road, Malleshwaram, Bengaluru"),
    "CineVerse VR Bengaluru": ("PVR: VR Bengaluru", "Bengaluru Urban", "VR Bengaluru, Whitefield Road, Mahadevapura, Bengaluru"),
    "CineVerse GT World Mall": ("GT World Cinemas", "Bengaluru Urban", "GT World Mall, Magadi Main Road, Bengaluru"),
    "CineVerse Elements Mall": ("PVR: Elements Mall", "Bengaluru Urban", "Elements Mall, Thanisandra Main Road, Nagavara, Bengaluru"),
    "CineVerse Gopalan Arcade": ("Gopalan Cinemas: Arcade Mall", "Bengaluru Urban", "Gopalan Arcade Mall, Mysore Road, Bengaluru"),
    "CineVerse Lulu Global Mall": ("PVR: Lulu Mall Bengaluru", "Bengaluru Urban", "Lulu Global Mall, Mysore Road, Rajajinagar, Bengaluru"),
}
